### ISSUE TITLE
Two security vulnerabilities with vm2 <= 3.9.17

### ISSUE THREAD

**Issue by jwkellyiii** [boschni/json-merger#49]
There are two critical security vulnerabilities with `vm2` <= 3.9.17. `vm2` has released 3.9.19. Could we get a version bump that includes this update?

1. vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-whpj-8f3w-67p5
2. vm2 vulnerable to Inspect Manipulation - https://github.com/advisories/GHSA-p5gc-c584-jj6v

**Comment by Marzz3** [comment]
VM2 has been deprecated and remains vulnerable.  See note from author recommending isolated-vm as a replacement.  
![image](https://github.com/boschni/json-merger/assets/127155231/bad812b8-4ef5-4de6-8c30-b52f2f48a4fd)

**Comment by rnwalker7** [comment]
I have forked the repo and published to the NPM Registry.
Source is here: https://github.com/rnwalker7/json-merger
NPM Registry: https://www.npmjs.com/package/@rnwalker7/json-merger

If @boschni does come back online and wishes to resume maintenance, I will gladly merge any changes I make back into his code base. But for now, let's stay safe.

**Comment by boschni** [comment]
Sorry guys for not responding. I'm not actively maintaining these packages anymore but I do feel bad about having a package published with security vulnerabilities.

I have replaced `vm2` with `node:vm` as you suggested but also put the `$expression` operation behind a configuration flag because using node:vm can execute untrusted code which could result in a security risk depending on the situation. Bumped the version to `2.0.0` because this is a breaking change.

Thank you for putting in the effort @gdavidkov and @rnwalker7 and feel free to maintain the fork though if you want to add more functionality to it.
